name: 🐞 Bug Report
description: Describe your problem or unwanted behavior with config-client.
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where are you using config-client?
      options:
        - Linux
        - Mac
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. step one
        2. step two
        3. step thee
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please 🙏.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks
    validations:
      required: false
